---
- name: Rancher server is started
  docker_container:
    name: "{{ rancher_name }}"
    image: rancher/server
    state: started
    restart_policy: always
    restart_retries: 3
    ports:
      - "{{ rancher_port }}:8080"
  tags:
    - rancher_server

- name: Rancher server is listening
  action: command docker logs {{ rancher_name }}
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 30
  delay: 10
  tags:
    - rancher_server

- name: Print Rancher's URL
  debug: msg="You can connect to rancher server http://{{ ansible_default_ipv4.address }}:{{ rancher_port }}"
  tags:
    - rancher_server

